#!/bin/sh
# $Id: init,v 1.3 2004/03/16 01:43:45 zal Exp $
#
# Script to remove stale screen named pipes on bootup.
#
set -e

SCREENDIR=/var/run/screen

case "$1" in
start)
    if find $SCREENDIR -type p | grep '^' >/dev/null; then
        echo -n 'Cleaning up stale screen sessions... '
        find $SCREENDIR -type p -print0 | xargs -0 rm -f
        echo "done."
    fi
    ;;
stop|restart|reload|force-reload)
    ;;
esac

exit 0
