#!/bin/sh
# $Id: init,v 1.3 2004/03/16 01:43:45 zal Exp $
#
# Script to remove stale screen named pipes on bootup.
#

### BEGIN INIT INFO
# Provides:          screen-cleanup
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: screen sessions cleaning
### END INIT INFO

set -e

SCREENDIR=/var/run/screen

case "$1" in
start)
    if ! test -d $SCREENDIR; then
        mkdir $SCREENDIR
        chown root:utmp $SCREENDIR
    fi
    find $SCREENDIR -type p -print0 | xargs -0r rm -f --
# If the local admin has used dpkg-statoverride to install screen setuid,
# change the permissions of /var/run/screen accordingly
    if [ `stat -c%a /usr/bin/screen` -ge 4000 ]; then
        chmod 0755 $SCREENDIR
    else
        chmod 0775 $SCREENDIR
    fi
    ;;
stop|restart|reload|force-reload)
    ;;
esac

exit 0
