#! /bin/sh
install-info --quiet --remove screen

#if a user later wants to install an old version of screen 
#(like 3.6.2), that version will expect /tmp/screens to have different
#permissions than it has now, so we remove it now:

if test "$1" = "remove"; then
  rm -rf /tmp/screens
fi
